-- ============================================
-- 此文件由 OneDay Cloud 自动生成，请勿手动修改
-- This file is auto-generated by OneDay Cloud, DO NOT MODIFY
-- ============================================

create table public.ai_invest_snapshots (
  snapshot_date date primary key,
  day_n int not null,
  payload jsonb not null,
  created_at timestamptz default now()
);

alter table public.ai_invest_snapshots enable row level security;

create policy "anon read" on public.ai_invest_snapshots
  for select using (true);